In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train_set.csv', index_col=0)

In [3]:
df.shape

(3915, 72)

In [5]:
df

Month 1   Month 2   Month 3   Month 4   Month 5   Month 6  \
Region_Name                                                               
Region 1     0.154324  0.122901  0.127583  0.501557  0.103551  0.051983   
Region 2     0.119708  0.119831  0.112970  0.326049  0.098852  0.041502   
Region 3     0.178236  0.165497  0.190754  0.321733  0.203126  0.048345   
Region 4     0.225016  0.220602  0.224240  0.330916  0.268934  0.171322   
Region 5     0.318976  0.316835  0.328486  0.483001  0.380898  0.292074   
...               ...       ...       ...       ...       ...       ...   
Region 3911  3.400484  3.999567  3.308452  2.636698  2.191918  2.392276   
Region 3912  0.374751  0.478654  0.501871  0.481275  0.436495  0.252011   
Region 3913  0.463527  0.571315  0.644025  0.636814  0.496774  0.233639   
Region 3914  1.641510  1.649937  2.110449  1.642345  1.002016  1.003032   
Region 3915  0.307089  0.451604  0.448063  0.464692  0.384780  0.243672   

              Month 7   Month 8   Month 9  Month 10  ...  Month 63  Month 64  \
Region_Name                                          ...                       
Region 1     0.140272  0.157586  0.182546  0.181801  ...  0.336913  0.321828   
Region 2     0.116759  0.136964  0.178476  0.162621  ...  0.283412  0.302669   
Region 3     0.180064  0.176990  0.224173  0.223810  ...  0.331988  0.377643   
Region 4     0.243672  0.219831  0.242115  0.227575  ...  0.315252  0.329762   
Region 5     0.268395  0.326809  0.344086  0.278257  ...  0.366314  0.392924   
...               ...       ...       ...       ...  ...       ...       ...   
Region 3911  2.367559  2.481581  2.195076  4.450618  ...  3.321083  3.205348   
Region 3912  0.207955  0.262587  0.311456  0.451421  ...  1.061902  0.996507   
Region 3913  0.140339  0.252526  0.318680  0.396993  ...  1.196925  1.245373   
Region 3914  0.721615  0.725879  0.706506  1.940017  ...  1.930428  1.826249   
Region 3915  0.151615  0.268620  0.384472  0.384382  ...  0.773679  0.823657   

             Month 65  Month 66  Month 67  Month 68  Month 69  Month 70  \
Region_Name                                                               
Region 1     0.321895  0.337018  0.121581  0.234171  0.294693  0.373754   
Region 2     0.306597  0.327412  0.124563  0.218367  0.275179  0.344997   
Region 3     0.384990  0.362927  0.230516  0.263643  0.296751  0.400269   
Region 4     0.352229  0.368514  0.192878  0.228902  0.291502  0.364874   
Region 5     0.370159  0.422587  0.282631  0.289498  0.368923  0.416527   
...               ...       ...       ...       ...       ...       ...   
Region 3911  3.007797  2.388205  2.124475  2.733757  2.472169  3.531807   
Region 3912  1.074192  0.758227  0.657928  0.551515  0.604042  0.972735   
Region 3913  1.178635  0.860302  0.768423  0.560397  0.737536  1.207824   
Region 3914  1.682453  1.321538  1.027904  1.043067  1.123075  1.773948   
Region 3915  0.892410  0.569593  0.522356  0.467049  0.546029  0.817059   

             Month 71  Month 72  
Region_Name                      
Region 1     0.333642  0.242176  
Region 2     0.300503  0.215147  
Region 3     0.360406  0.335923  
Region 4     0.311379  0.271102  
Region 5     0.372523  0.392835  
...               ...       ...  
Region 3911  3.057962  3.118734  
Region 3912  0.947009  0.806398  
Region 3913  1.147999  0.768685  
Region 3914  1.640214  1.489277  
Region 3915  0.754813  0.542317  

[3915 rows x 72 columns]

In [6]:
df.dropna()

Month 1   Month 2   Month 3   Month 4   Month 5   Month 6  \
Region_Name                                                               
Region 1     0.154324  0.122901  0.127583  0.501557  0.103551  0.051983   
Region 2     0.119708  0.119831  0.112970  0.326049  0.098852  0.041502   
Region 3     0.178236  0.165497  0.190754  0.321733  0.203126  0.048345   
Region 4     0.225016  0.220602  0.224240  0.330916  0.268934  0.171322   
Region 5     0.318976  0.316835  0.328486  0.483001  0.380898  0.292074   
...               ...       ...       ...       ...       ...       ...   
Region 3911  3.400484  3.999567  3.308452  2.636698  2.191918  2.392276   
Region 3912  0.374751  0.478654  0.501871  0.481275  0.436495  0.252011   
Region 3913  0.463527  0.571315  0.644025  0.636814  0.496774  0.233639   
Region 3914  1.641510  1.649937  2.110449  1.642345  1.002016  1.003032   
Region 3915  0.307089  0.451604  0.448063  0.464692  0.384780  0.243672   

              Month 7   Month 8   Month 9  Month 10  ...  Month 63  Month 64  \
Region_Name                                          ...                       
Region 1     0.140272  0.157586  0.182546  0.181801  ...  0.336913  0.321828   
Region 2     0.116759  0.136964  0.178476  0.162621  ...  0.283412  0.302669   
Region 3     0.180064  0.176990  0.224173  0.223810  ...  0.331988  0.377643   
Region 4     0.243672  0.219831  0.242115  0.227575  ...  0.315252  0.329762   
Region 5     0.268395  0.326809  0.344086  0.278257  ...  0.366314  0.392924   
...               ...       ...       ...       ...  ...       ...       ...   
Region 3911  2.367559  2.481581  2.195076  4.450618  ...  3.321083  3.205348   
Region 3912  0.207955  0.262587  0.311456  0.451421  ...  1.061902  0.996507   
Region 3913  0.140339  0.252526  0.318680  0.396993  ...  1.196925  1.245373   
Region 3914  0.721615  0.725879  0.706506  1.940017  ...  1.930428  1.826249   
Region 3915  0.151615  0.268620  0.384472  0.384382  ...  0.773679  0.823657   

             Month 65  Month 66  Month 67  Month 68  Month 69  Month 70  \
Region_Name                                                               
Region 1     0.321895  0.337018  0.121581  0.234171  0.294693  0.373754   
Region 2     0.306597  0.327412  0.124563  0.218367  0.275179  0.344997   
Region 3     0.384990  0.362927  0.230516  0.263643  0.296751  0.400269   
Region 4     0.352229  0.368514  0.192878  0.228902  0.291502  0.364874   
Region 5     0.370159  0.422587  0.282631  0.289498  0.368923  0.416527   
...               ...       ...       ...       ...       ...       ...   
Region 3911  3.007797  2.388205  2.124475  2.733757  2.472169  3.531807   
Region 3912  1.074192  0.758227  0.657928  0.551515  0.604042  0.972735   
Region 3913  1.178635  0.860302  0.768423  0.560397  0.737536  1.207824   
Region 3914  1.682453  1.321538  1.027904  1.043067  1.123075  1.773948   
Region 3915  0.892410  0.569593  0.522356  0.467049  0.546029  0.817059   

             Month 71  Month 72  
Region_Name                      
Region 1     0.333642  0.242176  
Region 2     0.300503  0.215147  
Region 3     0.360406  0.335923  
Region 4     0.311379  0.271102  
Region 5     0.372523  0.392835  
...               ...       ...  
Region 3911  3.057962  3.118734  
Region 3912  0.947009  0.806398  
Region 3913  1.147999  0.768685  
Region 3914  1.640214  1.489277  
Region 3915  0.754813  0.542317  

[3915 rows x 72 columns]

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [8]:
linmodel = LinearRegression()
rmf = RandomForestRegressor(n_estimators=200)

In [9]:
x1, x2, x3, y = df['Month 71'], df['Month 70'], df['Month 69'], df['Month 72']
x1, x2, x3, y = np.array(x1), np.array(x2), np.array(x3), np.array(y)
x1, x2, x3, y = x1.reshape(-1, 1), x2.reshape(-1, 1), x3.reshape(-1, 1), y.reshape(-1, 1)
final_x = np.concatenate((x1, x2, x3), axis=1)
print(final_x)

[[0.3336417  0.37375369 0.29469256]
 [0.30050302 0.34499689 0.27517875]
 [0.36040647 0.40026859 0.29675056]
 ...
 [1.1479989  1.20782415 0.73753595]
 [1.64021404 1.77394841 1.12307464]
 [0.75481252 0.81705893 0.546029  ]]


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.iloc[:, 0:71]

In [12]:
y = df['Month 72']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33)

In [14]:
rmf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200)

In [15]:
linmodel.fit(X_train, y_train)

LinearRegression()

In [16]:
pred = rmf.predict(X_test)
pred = linmodel.predict(X_test)

In [18]:
pred = linmodel.predict(X_test)